### PR TITLE
Removing transmitter supplied fields from stream config PUT and PATCH…

### PR DESCRIPTION
**Pull request by ysarig1**
Removed the transmitter supplied fields from the stream config PUT and PATCH examples.

### CODE REVIEW

**Comment by ysarig1** [comment]
@FragLegs, @appsdesh, @atultulshi Can you please review the PR and approve/comment?

**Review by appsdesh — CHANGES_REQUESTED** [review]
The existing language already clarifies -

> Transmitter-Supplied properties beside the stream_id MAY be present,
but they MUST match the expected value. Missing Transmitter-Supplied
properties MUST be ignored by the Transmitter.

There may be reasons for the receiver to send the same values to make sure it's info matches the Tx info (and expect to receive error message)

I don't think this PR is needed. Please let me know your thoughts

**Comment by ysarig1** [comment]
> The existing language already clarifies -
> 
> > Transmitter-Supplied properties beside the stream_id MAY be present,
> > but they MUST match the expected value. Missing Transmitter-Supplied
> > properties MUST be ignored by the Transmitter.
> 
> There may be reasons for the receiver to send the same values to make sure it's info matches the Tx info (and expect to receive error message, on mismatch)
> 
> I don't think this PR is needed. Please let me know your thoughts

The issue addressed by this PR is not if the fields can or can't be in the request but the fact that having a the fields in the **examples** is confusing. Having transmitter-supplied fields in an update request is an edge case and while it is allowed, it doesn't make sense to do so.

**Review by FragLegs — APPROVED** [review]
Thanks for working on this!

**Review by tulshi — APPROVED** [review]

**Pull request merged**
