### PR TITLE
removed duplicate status descriptions

### PR DESCRIPTION
**Pull request by tulshi**

### CODE REVIEW

**Review by FragLegs — CHANGES_REQUESTED** [review]
This change removes any description of what the enabled, paused, and disabled states mean. I think we need to at least describe the expected behavior for the Transmitter in each state.

**Comment by tulshi** [comment]
> This change removes any description of what the enabled, paused, and disabled states mean. I think we need to at least describe the expected behavior for the Transmitter in each state.

Do the descriptions in 7.1.2 suffice to describe each state?

**Comment by FragLegs** [comment]
7.1.2 only talks about what the Transmitter should do if it decides to change the stream status without the Receiver's input. It doesn't describe at all what the states mean or what the Transmitter is expected to do in each state.

**Comment by tulshi** [comment]
PR incorrectly removes text that is required in the spec

**Pull request closed without merging**
